In [2]:
#Assignment 2: Machine Learning
#Name: Uday Bhaskar Valapadasu
#ID: 11696364

In [7]:
#Import Statements

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import warnings
# Suppress the FutureWarning
warnings.simplefilter(action='ignore', category=FutureWarning)

In [8]:
# Using the diabetes_df.csv created from assignment - 1 & Created a Pandas dataframe from diabetes_df.csv and named it assignment2_df

 
assignment2_df = pd.read_csv("diabetes_df.csv")
assignment2_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Target
0,6,148,72,35,150,33.6,0.627,50,1
1,3,78,50,32,88,31.0,0.248,26,1
2,2,197,70,45,543,30.5,0.158,53,1
3,1,189,60,23,846,30.1,0.398,59,1
4,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
145,1,147,94,41,150,49.3,0.358,27,1
146,3,187,70,22,200,36.4,0.408,36,1
147,8,154,78,32,150,32.4,0.443,45,1
148,1,128,88,39,110,36.5,1.057,37,1
149,9,170,74,31,150,44.0,0.403,43,1

In [9]:
# Setup the Machine Learning Model:
#Dividing the data into features (X) array and target (y) array.

#features array
X = assignment2_df.drop(['Target'], axis=1)
#target array 
y = assignment2_df['Target']

In [19]:
# Splitting the dataset into 80-20, 70-30, and 60-40 ratios. (Example: 80-20 means, 80% training data, 20% testing data, and so on.)

#Split-1 into 80-20
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.2, random_state=42)

#Split-2 into 70-30
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.3, random_state=42)

#Split-3 into 60-40
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y, test_size=0.3, random_state=42)

In [20]:
# For each data split, apply logistic regression machine learning model to build confusion matrix and accuracy estimates.
# So, importing the necessary accordinhly.

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [21]:
#Operation Performing on Split-1 (80-20)

lr_split_1 = LogisticRegression(random_state=42)
lr_split_1.fit(X_train1, y_train1)

NameError: name 'y_train1' is not defined

In [14]:
#2. Drop records with missing data (0, empty column values, NaN, etc.).
# For each command, print “# of records removed”.
# Print “zero records removed” if the condition is not met.

initial_dataset_count = len(diabetes_df)

# Drop rows with NaN values
diabetes_df = diabetes_df.dropna()
after_dropped_nan_count = len(diabetes_df)
print(f"# of records removed (NaN): {initial_dataset_count - after_dropped_nan_count}")

# Drop rows with empty strings
diabetes_df = diabetes_df[~(diabetes_df == '').any(axis=1)]
after_dropped_empty_string_count = len(diabetes_df)
print(f"# of records removed (empty values): {after_dropped_nan_count - after_dropped_empty_string_count}")

total_removed = initial_dataset_count - after_dropped_empty_string_count
if total_removed == 0:
    print("zero records removed")
else:
    print(f"Total # of records removed: {total_removed}")

NameError: name 'diabetes_df' is not defined

In [61]:
# Here I have performed the replace insulin before drop rows with 0 value operation, Because according to the question if, we do the drop rows with 
# missing values in step 2 i.e 0 then there is no use of doing the 3rd step i.e 'Replace column values where Insulin is 0 with 150'
# because the rows with 0 values are already deleted in step 2. We are trying to replace 0 with 150 in column "Insulin".


# Replace Insulin values that are 0 with 150
insulinRCount = (diabetes_df['Insulin'] == 0).sum()
diabetes_df.loc[diabetes_df['Insulin'] == 0, 'Insulin'] = 150
print(f"# of records were updated with new data for insulin: {insulinRCount}")

initial_count = len(diabetes_df)

# Drop rows with 0 values
diabetes_df = diabetes_df[~(diabetes_df == 0).any(axis=1)]
after_dropping_zero_count = len(diabetes_df)
print(f"# of records removed (0 values): {initial_count - after_dropping_zero_count}")

# of records were updated with new data for insulin: 374
# of records removed (0 values): 618

In [49]:
#4.Rename column 'Outcome' to 'Target'
diabetes_df = diabetes_df.rename(columns={'Outcome': 'Target'})

# Writing the updated dataframe and Saving it to the updated DataFrame to a new CSV file 
diabetes_df.to_csv('diabetes_df.csv', index=False)

# Print the updated DataFrame
print("\nUpdated DataFrame:")
print(diabetes_df)

Updated DataFrame:
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35      150  33.6
6              3       78             50             32       88  31.0
8              2      197             70             45      543  30.5
13             1      189             60             23      846  30.1
14             5      166             72             19      175  25.8
..           ...      ...            ...            ...      ...   ...
746            1      147             94             41      150  49.3
748            3      187             70             22      200  36.4
754            8      154             78             32      150  32.4
755            1      128             88             39      110  36.5
761            9      170             74             31      150  44.0

     DiabetesPedigreeFunction  Age  Target
0                       0.627   50       1
6                       0.248   26       1
8                       0.158   53       1
13                      0.398   59       1
14                      0.587   51       1
..                        ...  ...     ...
746                     0.358   27       1
748                     0.408   36       1
754                     0.443   45       1
755                     1.057   37       1
761                     0.403   43       1

[150 rows x 9 columns]